# Generated by Django 5.2.5 on 2025-08-27 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recording',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tourview',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.AlterUniqueTogether(
            name='tourstep',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tourview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tour',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tourstep',
            name='step_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['status'], name='tours_tour_status_77f792_idx'),
        ),
        migrations.AddIndex(
            model_name='tour',
            index=models.Index(fields=['privacy'], name='tours_tour_privacy_432380_idx'),
        ),
        migrations.AddConstraint(
            model_name='tourstep',
            constraint=models.UniqueConstraint(fields=('tour', 'step_number'), name='unique_step_per_tour'),
        ),
        migrations.AddConstraint(
            model_name='tourview',
            constraint=models.UniqueConstraint(fields=('tour', 'viewer', 'ip_address'), name='unique_view_per_user'),
        ),
    ]
